### ISSUE TITLE
Colors are different from screenshots

### ISSUE THREAD

**Issue by jchook** [MaxGraey/atom-dark-fusion-syntax#10]
I installed atom-dark-fusion-syntax and Nucleus UI as described in the readme, but the colors (especially background) are way different.

Here is an actual screenshot of me looking at the README from Atom. You can see here that my background appears blue (#2B303C) while your screenshot is more gray (#33333D).

![screen shot 2017-04-29 at 4 16 58 pm](https://cloud.githubusercontent.com/assets/193530/25558570/74666e2c-2cf7-11e7-910b-7abff668655c.png)

I'm using Atom 1.16.0 x64 on Mac OS 10.12.4 (16E195).

**Comment by MaxGraey** [comment]
Yes. I'll update screenshots ASAP

**Comment by jchook** [comment]
Personally I strongly prefer the less blue background.

**Comment by JavierFajado** [comment]
I agree with jchook, the version in the screenshots are nicer to read in my opinion :)

**Comment by jpinnix** [comment]
Your screenshots have the background color:
#32343E — Shark

Mine shows up as:
#2F3643 — Bunting

I've not noticed it until I started trying to compare with your screenshots.

**Comment by MaxGraey** [comment]
Yeah, screenshots should update. But I working on next version which have slightly different colours again.

**Comment by jpinnix** [comment]
I look forward to the next version!
